### ISSUE TITLE
Replace RxJava's Action0 with a plain Runnable

### ISSUE THREAD

**Issue by eleventigers** [coursera/shift#1]
Dependency on RxJava only for its `Action0` is questionable since the native `Runnable` can do exactly the same. While it might be convenient to use RxJava's types when using Shift within RxJava heavy app, this library does not really utilise RxJava. If there is a big need to provide RxJava support it would be better to provide such feature in a separate module/package.

**Comment by StanleyFung** [comment]
Thanks for the suggestion! Made the change.
