### ISSUE TITLE
ShiftPref implementations do not save their initial value until their value is changed

### ISSUE THREAD

**Issue by BenSchwab** [coursera/shift#2]
There are many snappyDB exceptions caused by the initial value of the ShiftPref not being stored to persistence. The only time the value is stored, is when shift preference is changed in the floating menu. When large number of shift preferences are used, the sudden influx of db exceptions can cause weird bugs, including SegFaults.

**Comment by StanleyFung** [comment]
Your PR has been merged :+1:
